language: python

python:
    - "2.7"

env:
    - PYTHON=2.7 DEPS=full TEST=standard
    - PYTHON=2.7 DEPS=minimal TEST=standard
    - PYTHON=3.4 DEPS=full TEST=standard _EXPYFUN_SILENT=true
    - PYTHON=3.4 DEPS=minimal TEST=extra
    # The _EXPYFUN_SILENT is a workaround for a silly Py3/Travis bug

virtualenv:
    system_site_packages: true

before_install:
    # Easy dependencies (pulseaudio, scipy, matplotlib, nose, coverage, coveralls, flake8)
    # Only use Pulseaudio on 2.7 because on Travis 3.3 causes some strange error...
    - travis_retry sudo apt-get update -qq
    - if [ "${PYTHON}" == "2.7" ]; then
        travis_retry sudo apt-get install -qq -y pulseaudio python-nose python-coverage python-scipy python-matplotlib;
        dbus-launch pulseaudio --start;
        travis_retry sudo pip install -q coveralls;
      else
        wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh;
        chmod +x miniconda.sh;
        ./miniconda.sh -b;
        export PATH=/home/$USER/anaconda/bin:$PATH;
        conda update --yes conda;
        conda create -n testenv --yes --quiet pip python=$PYTHON;
        source activate testenv;
        conda install --yes --quiet scipy matplotlib nose coverage;
        travis_retry pip install -q coveralls;
      fi;
    - python --version
    # Only install these deps if necessary (slow on Py3k)
    - if [ "${TEST}" == "extra" ]; then
        travis_retry pip install -q flake8;
      else
        travis_retry pip install -q nose-timer http://pyglet.googlecode.com/archive/tip.zip;
      fi;
    # Full dependencies (pandas, mne-python, pytables, joblib)
    - SRC_DIR=${PWD}
    - cd ~
    - if [ "${DEPS}" == "full" ]; then
        if [ "${PYTHON}" == "2.7" ]; then
          sudo apt-get install -qq -y python-pandas python-tables python-joblib;
        else
          conda install --yes --quiet pandas pytables joblib;
        fi;
        pip install mne;
      fi;
    - sudo ldconfig;
    # We need to create a (fake) display on Travis, let's use a funny resolution
    # This must be done before importing expyfun, since Pyglet needs it
    - export DISPLAY=:99.0
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset

install:
    - cd ${SRC_DIR}
    - if [ "${TEST}" != "extra" ]; then
        python setup.py install;
      fi;

script:
    - if [ "${TEST}" == "extra" ]; then
        make flake;
      else
        nosetests --with-timer --timer-top-n=5;
      fi;

after_success:
    # Need to run from source dir to execute appropriate "git" commands
    - coveralls
